[project]
name = "hokuyolaser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=4.10.0.84",
    "pyinstaller>=6.11.0",
    "python-osc>=1.9.0",
    "python-tuio>=0.0.9",
    "setuptools>=75.2.0",
]
